// Template definitions: E-commerce, Import & Export, Healthcare, Construction,
// Food, Travel & Events, Nonprofit
const B = require('./seed_fields');
const { sender, party, fields, group, signBlock, docMeta, letter, form, report, planner, table, checklist, moneyDoc, agreement } = B;
const { text, long, num, cur, date, email, phone, sel, img, check, addr } = B;

const T = (slug, name, cat, doc, desc, sections, opts = {}) =>
  ({ slug, name, category: cat, docType: doc, description: desc, sections, tags: opts.tags || [], featured: !!opts.featured, disclaimer: opts.disclaimer });

module.exports = [

  // ============ E-COMMERCE ============
  T('product-spec-sheet', 'Product Specification Sheet', 'ecommerce', 'form',
    'Technical spec sheet describing a product\u2019s features and details.',
    form('main', 'Product', [
      text('name', 'Product Name', { required: true }), text('sku', 'SKU / Code'),
      text('brand', 'Brand'), text('category', 'Category'),
      cur('price', 'Price'), text('weight', 'Weight'), text('dims', 'Dimensions'),
      long('desc', 'Description', { span: 2 }), long('features', 'Key Features', { span: 2 }),
      long('specs', 'Technical Specifications', { span: 2 }),
    ], ), { tags: ['product', 'spec', 'specification', 'ecommerce'] }),
  T('product-listing', 'Product Listing Template', 'ecommerce', 'form',
    'Listing template for marketplace or catalog product entries.',
    form('main', 'Listing', [
      text('name', 'Product Title', { required: true }), text('sku', 'SKU'),
      text('category', 'Category'), cur('price', 'Price'), num('stock', 'Stock'),
      long('desc', 'Description', { span: 2 }), long('bullets', 'Bullet Points', { span: 2 }),
      long('keywords', 'Search Keywords', { span: 2 }),
    ], ), { tags: ['product', 'listing', 'marketplace', 'ecommerce'] }),
  T('product-comparison', 'Product Comparison Sheet', 'ecommerce', 'table',
    'Side-by-side comparison of products by feature and price.',
    table('Comparison', [text('feature', 'Feature', { span: 2 }), text('a', 'Product A'), text('b', 'Product B'), text('c', 'Product C')]),
    { tags: ['comparison', 'product', 'versus', 'ecommerce'] }),
  T('packing-list', 'Packing List', 'ecommerce', 'table',
    'Shipment packing list with item quantities and weights.',
    table('Packed Items', [text('desc', 'Item Description', { span: 2 }), num('qty', 'Qty'), text('weight', 'Weight'), text('box', 'Box / Carton')]),
    { tags: ['packing', 'list', 'shipping', 'order'] }),
  T('shipping-checklist', 'Shipping Checklist', 'ecommerce', 'checklist',
    'Pre-dispatch checklist for order fulfillment.',
    checklist('Shipping Steps'), { tags: ['shipping', 'checklist', 'fulfillment'] }),
  T('return-form', 'Return Form', 'ecommerce', 'form',
    'Customer return authorization form with reason and refund details.',
    form('main', 'Return Request', [
      text('name', 'Customer Name', { required: true }), text('order', 'Order No.'),
      email(), phone(),
      text('item', 'Item(s) to Return', { span: 2 }),
      sel('reason', 'Reason', ['Defective', 'Wrong Item', 'Not as Described', 'Changed Mind', 'Other']),
      sel('resolution', 'Preferred Resolution', ['Refund', 'Replacement', 'Store Credit']),
      long('details', 'Details', { span: 2 }),
    ]), { tags: ['return', 'rma', 'refund', 'ecommerce'] }),
  T('refund-request', 'Refund Request Form', 'ecommerce', 'form',
    'Request a refund for a purchase with reason and payment details.',
    form('main', 'Refund Request', [
      text('name', 'Customer Name', { required: true }), text('order', 'Order No.'),
      email(), cur('amount', 'Amount'), date('purchase', 'Purchase Date'),
      long('reason', 'Reason for Refund', { span: 2 }),
    ]), { tags: ['refund', 'request', 'money back', 'ecommerce'] }),
  T('inventory-sheet', 'Inventory Sheet', 'ecommerce', 'table',
    'Track stock levels, reorder points and supplier info.',
    table('Inventory', [text('item', 'Item', { span: 2 }), text('sku', 'SKU'), num('qty', 'In Stock'), num('reorder', 'Reorder At'), cur('cost', 'Unit Cost')]),
    { tags: ['inventory', 'stock', 'ecommerce', 'warehouse'] }),
  T('stock-tracker', 'Stock Tracker', 'ecommerce', 'table',
    'Log stock movements in and out with dates and quantities.',
    table('Movements', [date('day', 'Date'), text('item', 'Item', { span: 2 }), num('in', 'Qty In'), num('out', 'Qty Out'), num('balance', 'Balance')]),
    { tags: ['stock', 'tracker', 'inventory', 'ecommerce'] }),

  // ============ IMPORT & EXPORT ============
  T('intl-commercial-invoice', 'Commercial Invoice (International)', 'import-export', 'invoice',
    'Commercial invoice for customs: origin, Incoterms, HS codes.',
    moneyDoc({ meta: [text('no', 'Invoice No.'), date(), text('country', 'Country of Origin'), text('incoterm', 'Incoterms'), text('awb', 'AWB / B-L No.')] }),
    { tags: ['commercial', 'invoice', 'export', 'customs', 'international'] }),
  T('intl-proforma-invoice', 'Proforma Invoice (International)', 'import-export', 'invoice',
    'Proforma invoice for international buyers before shipment.',
    moneyDoc({ meta: [text('no', 'Proforma No.'), date(), date('valid', 'Valid Until'), text('incoterm', 'Incoterms')] }),
    { tags: ['proforma', 'invoice', 'export', 'import'] }),
  T('intl-packing-list', 'Export Packing List', 'import-export', 'table',
    'Detailed packing list with cartons, weights and dimensions.',
    table('Contents', [text('desc', 'Description', { span: 2 }), num('qty', 'Qty'), text('gw', 'Gross Weight'), text('dims', 'Dimensions'), text('marks', 'Marks')]),
    { tags: ['packing', 'list', 'export', 'shipping'] }),
  T('intl-purchase-order', 'Import Purchase Order', 'import-export', 'invoice',
    'Purchase order for international suppliers with shipping terms.',
    moneyDoc({ company: 'Importer', client: 'Supplier', meta: [text('no', 'PO No.'), date(), text('incoterm', 'Incoterms'), date('deliver', 'Required By')] }),
    { tags: ['purchase', 'order', 'import', 'supplier'] }),
  T('shipping-instructions', 'Shipping Instructions', 'import-export', 'form',
    'Instructions to freight forwarder covering handling and routing.',
    form('main', 'Shipment', [
      text('shipper', 'Shipper', { required: true }), text('consignee', 'Consignee'),
      text('notify', 'Notify Party'), text('port', 'Port of Loading'),
      text('discharge', 'Port of Discharge'), text('incoterm', 'Incoterms'),
      long('goods', 'Goods Description', { span: 2 }),
      long('special', 'Special Instructions', { span: 2 }),
    ]), { tags: ['shipping', 'instructions', 'freight', 'export'] }),
  T('shipment-checklist', 'Shipment Checklist', 'import-export', 'checklist',
    'Pre-shipment documentation and compliance checklist.',
    checklist('Documents & Tasks'), { tags: ['shipment', 'checklist', 'export', 'docs'] }),
  T('freight-quote-request', 'Freight Quote Request', 'import-export', 'form',
    'Request freight quotes from carriers and forwarders.',
    form('main', 'Shipment Details', [
      text('origin', 'Origin'), text('dest', 'Destination'),
      text('goods', 'Commodity'), text('weight', 'Total Weight'),
      text('volume', 'Volume / CBM'), num('packages', 'Packages'),
      sel('mode', 'Mode', ['Sea', 'Air', 'Road', 'Rail']),
      date('ready', 'Ready Date'), text('incoterm', 'Incoterms'),
      long('notes', 'Notes', { span: 2 }),
    ]), { tags: ['freight', 'quote', 'shipping', 'logistics'] }),
  T('delivery-order', 'Delivery Order', 'import-export', 'form',
    'Order authorizing release of cargo to the consignee.',
    form('main', 'Delivery Order', [
      text('no', 'DO No.'), date(), text('bl', 'B-L / AWB No.'),
      text('consignee', 'Consignee', { required: true }), text('vessel', 'Vessel / Flight'),
      long('goods', 'Goods / Containers', { span: 2 }),
      text('location', 'Pickup Location'), date('pickup', 'Pickup Date'),
    ]), { tags: ['delivery', 'order', 'cargo', 'import'] }),

  // ============ HEALTHCARE / CLINICS ============
  T('patient-registration', 'Patient Registration Form', 'healthcare', 'form',
    'Clinic intake form for new patient registration.',
    form('main', 'Patient Information', [
      text('name', 'Full Name', { required: true }), date('dob', 'Date of Birth'),
      sel('gender', 'Gender', ['Male', 'Female', 'Other']),
      phone(), email(), addr(),
      text('insurance', 'Insurance Provider'), text('policy', 'Policy No.'),
      long('emergency', 'Emergency Contact (name & phone)', { span: 2 }),
      check('consent', 'I consent to treatment and data processing'),
    ]), { tags: ['patient', 'registration', 'clinic', 'intake'] }),
  T('appointment-form', 'Appointment Form', 'healthcare', 'form',
    'Book or record a clinic appointment.',
    form('main', 'Appointment', [
      text('name', 'Patient Name', { required: true }), phone(),
      text('doctor', 'Doctor / Department'), date('day', 'Preferred Date'),
      text('time', 'Preferred Time'),
      sel('type', 'Visit Type', ['New Patient', 'Follow-up', 'Consultation', 'Emergency']),
      long('reason', 'Reason for Visit', { span: 2 }),
    ], ), { tags: ['appointment', 'booking', 'clinic', 'doctor'] }),
  T('patient-information', 'Patient Information Form', 'healthcare', 'form',
    'Detailed patient record: history, medications, allergies.',
    form('main', 'Patient Details', [
      text('name', 'Full Name', { required: true }), date('dob', 'Date of Birth'),
      phone(), addr(),
      long('history', 'Medical History', { span: 2 }),
      long('meds', 'Current Medications', { span: 2 }),
      long('allergies', 'Allergies', { span: 2 }),
    ]), { tags: ['patient', 'information', 'medical', 'clinic'] }),
  T('clinic-invoice', 'Clinic Invoice', 'healthcare', 'invoice',
    'Invoice for clinic services and treatments.',
    moneyDoc({ company: 'Clinic', client: 'Patient', meta: [text('no', 'Invoice No.'), date(), text('patient', 'Patient ID')] }),
    { tags: ['invoice', 'clinic', 'billing', 'medical'] }),
  T('referral-letter', 'Referral Letter', 'healthcare', 'letter',
    'Letter referring a patient to a specialist or facility.',
    letter({ subject: 'Patient Referral', greeting: 'Dear Dr. [Name],' }),
    { tags: ['referral', 'letter', 'doctor', 'specialist'] }),

  // ============ CONSTRUCTION ============
  T('construction-quote', 'Construction Quote', 'construction', 'invoice',
    'Quotation for construction or renovation work.',
    moneyDoc({ client: 'Client', meta: [text('no', 'Quote No.'), date(), date('valid', 'Valid Until'), addr('site', 'Site Address')] }),
    { tags: ['quote', 'construction', 'estimate', 'building'] }),
  T('work-order', 'Work Order', 'construction', 'form',
    'Work order authorizing a job with scope and schedule.',
    [
      fields('main', 'Job Details', [text('no', 'Work Order No.'), date(), text('client', 'Client'), addr('site', 'Site Address'), text('supervisor', 'Supervisor'), date('due', 'Due Date')]),
      fields('work', 'Scope of Work', [long('scope', 'Work Description', { span: 2 }), long('materials', 'Materials Required', { span: 2 })]),
      signBlock(['Issued By', 'Accepted By']),
    ], { tags: ['work order', 'job', 'construction', 'service'] }),
  T('site-inspection', 'Site Inspection Checklist', 'construction', 'checklist',
    'Safety and quality inspection checklist for job sites.',
    [
      fields('main', 'Inspection', [addr('site', 'Site Address'), date(), text('inspector', 'Inspector')]),
      group('items', 'Inspection Points', [text('item', 'Item / Area', { span: 2 }), sel('status', 'Status', ['Pass', 'Fail', 'N/A']), text('note', 'Notes')], { addLabel: 'Add item', min: 10 }),
      signBlock(['Inspector']),
    ], { tags: ['inspection', 'site', 'safety', 'construction'] }),
  T('daily-site-report', 'Daily Site Report', 'construction', 'report',
    'Daily log of site work, labor, weather and incidents.',
    report({ meta: [text('title', 'Project Name', { required: true }), text('author', 'Supervisor'), date(), text('weather', 'Weather')] }),
    { tags: ['daily', 'report', 'site', 'construction'] }),
  T('contractor-invoice', 'Contractor Invoice', 'construction', 'invoice',
    'Invoice for contractor work with labor and material lines.',
    moneyDoc({ company: 'Contractor', client: 'Client', meta: [text('no', 'Invoice No.'), date(), text('job', 'Job Ref')] }),
    { tags: ['invoice', 'contractor', 'construction', 'billing'] }),
  T('safety-checklist', 'Safety Checklist', 'construction', 'checklist',
    'Workplace safety checklist for site compliance.',
    checklist('Safety Items'), { tags: ['safety', 'checklist', 'compliance', 'site'] }),

  // ============ RESTAURANTS & FOOD ============
  T('menu-template', 'Menu Template', 'food', 'table',
    'Simple printable menu with sections, items and prices.',
    table('Menu Items', [text('item', 'Item', { span: 2 }), text('desc', 'Description'), cur('price', 'Price'), text('section', 'Section')]),
    { tags: ['menu', 'restaurant', 'food', 'price'] }),
  T('restaurant-invoice', 'Restaurant Invoice', 'food', 'invoice',
    'Invoice or supplier billing for restaurants.',
    moneyDoc({ meta: [text('no', 'Invoice No.'), date()] }),
    { tags: ['invoice', 'restaurant', 'billing', 'food'] }),
  T('kitchen-checklist', 'Kitchen Checklist', 'food', 'checklist',
    'Daily kitchen prep and hygiene checklist.',
    checklist('Kitchen Tasks'), { tags: ['kitchen', 'checklist', 'restaurant', 'hygiene'] }),
  T('opening-checklist', 'Opening Checklist', 'food', 'checklist',
    'Opening duties checklist for restaurant staff.',
    checklist('Opening Tasks'), { tags: ['opening', 'checklist', 'restaurant', 'duties'] }),
  T('closing-checklist', 'Closing Checklist', 'food', 'checklist',
    'Closing duties checklist for restaurant staff.',
    checklist('Closing Tasks'), { tags: ['closing', 'checklist', 'restaurant', 'duties'] }),
  T('staff-schedule', 'Staff Schedule', 'food', 'planner',
    'Weekly staff rota with shifts and roles.',
    planner('Shifts', [text('name', 'Staff Member'), text('day', 'Day'), text('shift', 'Shift'), text('role', 'Role / Station')]),
    { tags: ['staff', 'schedule', 'rota', 'restaurant'] }),

  // ============ TRAVEL & EVENTS ============
  T('travel-itinerary', 'Travel Itinerary', 'travel-events', 'planner',
    'Day-by-day travel itinerary with flights, stays and activities.',
    planner('Itinerary', [date('day', 'Date'), text('place', 'Location'), text('activity', 'Plans / Bookings', { span: 2 }), text('note', 'Notes')]),
    { tags: ['travel', 'itinerary', 'trip', 'vacation'], featured: true }),
  T('packing-checklist', 'Packing Checklist', 'travel-events', 'checklist',
    'Travel packing checklist so nothing gets left behind.',
    checklist('Packing Items'), { tags: ['packing', 'checklist', 'travel', 'luggage'] }),
  T('travel-budget', 'Travel Budget', 'travel-events', 'table',
    'Trip budget for transport, stay, food and activities.',
    table('Budget', [text('cat', 'Category'), text('desc', 'Item / Notes'), cur('planned', 'Planned'), cur('actual', 'Actual')]),
    { tags: ['travel', 'budget', 'trip', 'expenses'] }),
  T('event-proposal', 'Event Proposal', 'travel-events', 'report',
    'Proposal for an event: concept, program, logistics and budget.',
    report({ meta: [text('title', 'Event Name', { required: true }), text('author', 'Organizer'), text('client', 'Client'), date('eventdate', 'Event Date')] }),
    { tags: ['event', 'proposal', 'planning'] }),
  T('event-budget', 'Event Budget', 'travel-events', 'table',
    'Budget sheet for events with categories and actuals.',
    table('Budget Items', [text('cat', 'Category'), text('desc', 'Item'), cur('planned', 'Planned'), cur('actual', 'Actual')]),
    { tags: ['event', 'budget', 'planning', 'costs'] }),
  T('event-checklist', 'Event Checklist', 'travel-events', 'checklist',
    'Complete event planning checklist from venue to vendors.',
    checklist('Event Tasks'), { tags: ['event', 'checklist', 'planning'] }),
  T('event-invitation', 'Event Invitation', 'travel-events', 'letter',
    'Formal invitation letter for events and functions.',
    letter({ subject: 'Invitation to [Event Name]', greeting: 'Dear [Guest Name],' }),
    { tags: ['invitation', 'event', 'letter', 'invite'] }),
  T('rsvp-form', 'RSVP Form', 'travel-events', 'form',
    'Guest RSVP form with attendance and dietary preferences.',
    form('main', 'RSVP', [
      text('name', 'Guest Name', { required: true }), email(), phone(),
      sel('attend', 'Attending?', ['Yes', 'No', 'Maybe']),
      num('guests', 'Number of Guests'),
      long('diet', 'Dietary Requirements', { span: 2 }),
      long('message', 'Message for the Host', { span: 2 }),
    ], ), { tags: ['rsvp', 'event', 'guest', 'form'] }),

  // ============ NONPROFIT / ORGANIZATIONS ============
  T('donation-receipt', 'Donation Receipt', 'nonprofit', 'receipt',
    'Receipt acknowledging a donation for donors and records.',
    B.receiptDoc(), { tags: ['donation', 'receipt', 'charity', 'nonprofit'] }),
  T('volunteer-application', 'Volunteer Application', 'nonprofit', 'form',
    'Application form for volunteers with availability and skills.',
    form('main', 'Volunteer Information', [
      text('name', 'Full Name', { required: true }), email(), phone(),
      date('dob', 'Date of Birth'), addr(),
      long('availability', 'Availability (days / hours)', { span: 2 }),
      long('skills', 'Skills & Interests', { span: 2 }),
      long('experience', 'Previous Volunteer Experience', { span: 2 }),
    ]), { tags: ['volunteer', 'application', 'nonprofit'] }),
  T('volunteer-agreement', 'Volunteer Agreement', 'nonprofit', 'agreement',
    'Agreement outlining volunteer role, expectations and conduct.',
    agreement({ a: 'Organization', b: 'Volunteer' }),
    { tags: ['volunteer', 'agreement', 'nonprofit'], disclaimer: true }),
  T('donation-form', 'Donation Form', 'nonprofit', 'form',
    'Pledge form for donations with amount and payment method.',
    form('main', 'Donor Information', [
      text('name', 'Donor Name', { required: true }), email(), phone(), addr(),
      cur('amount', 'Donation Amount'), sel('freq', 'Frequency', ['One-time', 'Monthly', 'Quarterly', 'Yearly']),
      sel('method', 'Payment Method', ['Bank Transfer', 'Card', 'Cash', 'Cheque']),
      check('anon', 'Keep my donation anonymous'),
    ]), { tags: ['donation', 'form', 'charity', 'pledge'] }),
  T('event-registration', 'Event Registration Form', 'nonprofit', 'form',
    'Registration form for organizational events and programs.',
    form('main', 'Registration', [
      text('name', 'Full Name', { required: true }), email(), phone(),
      text('org', 'Organization'), text('event', 'Event Name'),
      num('guests', 'Number of Attendees'),
      long('notes', 'Special Requirements', { span: 2 }),
    ], ), { tags: ['event', 'registration', 'nonprofit', 'form'] }),
  T('grant-proposal', 'Grant Proposal', 'nonprofit', 'report',
    'Grant proposal: mission, need, program plan and budget.',
    report({ meta: [text('title', 'Proposal Title', { required: true }), text('author', 'Organization'), text('funder', 'Funder'), cur('amount', 'Amount Requested'), date()] }),
    { tags: ['grant', 'proposal', 'funding', 'nonprofit'] }),
];
