// Template definitions: Real Estate, Legal, Marketing, Project Management
const B = require('./seed_fields');
const { sender, party, fields, group, signBlock, docMeta, letter, form, report, planner, table, checklist, moneyDoc, agreement } = B;
const { text, long, num, cur, date, email, phone, sel, img, check, addr } = B;

const T = (slug, name, cat, doc, desc, sections, opts = {}) =>
  ({ slug, name, category: cat, docType: doc, description: desc, sections, tags: opts.tags || [], featured: !!opts.featured, disclaimer: opts.disclaimer });

module.exports = [

  // ============ REAL ESTATE ============
  T('rental-agreement', 'Rental Agreement', 'real-estate', 'agreement',
    'Residential rental agreement covering rent, deposit and terms.',
    agreement({ a: 'Landlord', b: 'Tenant', details: [date('date', 'Agreement Date'), addr('property', 'Property Address'), cur('rent', 'Monthly Rent'), cur('deposit', 'Security Deposit'), text('term', 'Lease Term')] }),
    { tags: ['rental', 'agreement', 'landlord', 'tenant', 'lease'], featured: true, disclaimer: true }),
  T('lease-agreement', 'Lease Agreement', 'real-estate', 'agreement',
    'Fixed-term lease agreement for residential or commercial property.',
    agreement({ a: 'Lessor', b: 'Lessee', details: [date('date', 'Lease Date'), addr('property', 'Property Address'), cur('rent', 'Monthly Rent'), text('term', 'Lease Period')] }),
    { tags: ['lease', 'agreement', 'property', 'rent'], disclaimer: true }),
  T('property-inspection', 'Property Inspection Checklist', 'real-estate', 'checklist',
    'Room-by-room property condition inspection checklist.',
    [
      fields('main', 'Inspection Details', [addr('property', 'Property Address'), date(), text('inspector', 'Inspector'), text('tenant', 'Tenant')]),
      group('items', 'Inspection Items', [text('item', 'Area / Item', { span: 2 }), sel('cond', 'Condition', ['Good', 'Fair', 'Damaged', 'N/A']), text('note', 'Notes')], { addLabel: 'Add item', min: 10 }),
      signBlock(['Inspector', 'Tenant']),
    ], { tags: ['inspection', 'property', 'checklist', 'condition'] }),
  T('tenant-application', 'Tenant Application Form', 'real-estate', 'form',
    'Rental application collecting tenant, employment and reference info.',
    form('main', 'Applicant Information', [
      text('name', 'Full Name', { required: true }), date('dob', 'Date of Birth'),
      email(), phone(),
      text('employer', 'Employer'), text('income', 'Monthly Income'),
      addr('current', 'Current Address'), text('landlord', 'Current Landlord'),
      long('refs', 'References (name & phone)', { span: 2 }),
      check('consent', 'I authorize a background/credit check'),
    ]), { tags: ['tenant', 'application', 'rental', 'screening'] }),
  T('landlord-notice', 'Landlord Notice Letter', 'real-estate', 'letter',
    'Formal notice from landlord to tenant (entry, rent, termination).',
    letter({ subject: 'Notice to Tenant' }),
    { tags: ['landlord', 'notice', 'tenant', 'letter'] }),
  T('rent-receipt', 'Rent Receipt', 'real-estate', 'receipt',
    'Receipt acknowledging rent payment for a period.',
    B.receiptDoc(), { tags: ['rent', 'receipt', 'landlord', 'payment'] }),
  T('move-in-checklist', 'Move-In Checklist', 'real-estate', 'checklist',
    'Checklist for moving into a new property.',
    checklist('Move-In Tasks'), { tags: ['move in', 'checklist', 'property'] }),
  T('move-out-checklist', 'Move-Out Checklist', 'real-estate', 'checklist',
    'Checklist for moving out and handover of a property.',
    checklist('Move-Out Tasks'), { tags: ['move out', 'checklist', 'property'] }),

  // ============ LEGAL & AGREEMENTS ============
  T('non-disclosure-agreement', 'Non-Disclosure Agreement (NDA)', 'legal', 'agreement',
    'Mutual or one-way NDA protecting confidential information.',
    agreement({ a: 'Disclosing Party', b: 'Receiving Party' }),
    { tags: ['nda', 'confidentiality', 'agreement', 'legal'], featured: true, disclaimer: true }),
  T('service-agreement', 'Service Agreement', 'legal', 'agreement',
    'Agreement between a service provider and client for services rendered.',
    agreement({ a: 'Service Provider', b: 'Client' }),
    { tags: ['service', 'agreement', 'contract', 'legal'], disclaimer: true }),
  T('partnership-agreement', 'Partnership Agreement', 'legal', 'agreement',
    'Agreement defining roles, shares and responsibilities of partners.',
    agreement({ a: 'Partner 1', b: 'Partner 2' }),
    { tags: ['partnership', 'agreement', 'business', 'legal'], disclaimer: true }),
  T('freelance-agreement', 'Freelance Agreement', 'legal', 'agreement',
    'Agreement covering freelance scope, payment and IP ownership.',
    agreement({ a: 'Freelancer', b: 'Client' }),
    { tags: ['freelance', 'agreement', 'contract', 'legal'], disclaimer: true }),
  T('purchase-agreement', 'Purchase Agreement', 'legal', 'agreement',
    'Agreement for the sale and purchase of goods or assets.',
    agreement({ a: 'Seller', b: 'Buyer' }),
    { tags: ['purchase', 'agreement', 'sale', 'legal'], disclaimer: true }),
  T('employment-agreement', 'Employment Agreement', 'legal', 'agreement',
    'Employment terms between employer and employee.',
    agreement({ a: 'Employer', b: 'Employee' }),
    { tags: ['employment', 'agreement', 'contract', 'legal'], disclaimer: true }),
  T('contractor-agreement', 'Independent Contractor Agreement', 'legal', 'agreement',
    'Agreement for engaging an independent contractor.',
    agreement({ a: 'Company', b: 'Contractor' }),
    { tags: ['contractor', 'agreement', 'legal'] , disclaimer: true }),
  T('memorandum-of-understanding', 'Memorandum of Understanding (MOU)', 'legal', 'agreement',
    'Non-binding MOU recording mutual intent between two parties.',
    agreement({ a: 'Party A', b: 'Party B' }),
    { tags: ['mou', 'memorandum', 'understanding', 'legal'], disclaimer: true }),
  T('liability-waiver', 'Liability Waiver', 'legal', 'form',
    'Waiver releasing an organizer from liability for an activity.',
    [
      fields('main', 'Participant', [text('name', 'Full Name', { required: true }), date('dob', 'Date of Birth'), phone(), email()]),
      fields('activity', 'Activity', [text('activity', 'Activity / Event', { required: true }), text('organizer', 'Organizer'), date('date', 'Activity Date'), long('waiver', 'Waiver Text', { span: 2, default: 'I voluntarily assume all risks associated with this activity and release the organizer from any liability for injury, loss or damage to the fullest extent permitted by law.' })]),
      signBlock(['Participant Signature']),
    ], { tags: ['waiver', 'liability', 'release', 'legal'], disclaimer: true }),
  T('consent-form', 'Consent Form', 'legal', 'form',
    'General consent form for activities, data use or services.',
    [
      fields('main', 'Person Giving Consent', [text('name', 'Full Name', { required: true }), date('dob', 'Date of Birth'), phone(), email()]),
      fields('consent', 'Consent', [long('details', 'I consent to', { span: 2 }), check('agree', 'I have read and agree to the above'), date()]),
      signBlock(['Signature']),
    ], { tags: ['consent', 'form', 'permission', 'legal'], disclaimer: true }),
  T('declaration', 'Declaration Form', 'legal', 'form',
    'Formal declaration of facts made and signed by the declarant.',
    [
      fields('main', 'Declarant', [text('name', 'Full Name', { required: true }), addr(), text('id', 'ID / Passport No.')]),
      fields('decl', 'Declaration', [long('statement', 'I hereby declare that', { span: 2 }), date(), text('place', 'Place')]),
      signBlock(['Declarant Signature']),
    ], { tags: ['declaration', 'affidavit', 'legal', 'form'], disclaimer: true }),

  // ============ MARKETING ============
  T('marketing-plan', 'Marketing Plan', 'marketing', 'report',
    'Marketing plan: goals, audience, channels, budget and KPIs.',
    report({ meta: [text('title', 'Plan Title', { required: true }), text('author', 'Prepared By'), text('period', 'Period'), date()] }),
    { tags: ['marketing', 'plan', 'strategy'] }),
  T('marketing-proposal', 'Marketing Proposal', 'marketing', 'report',
    'Agency proposal covering strategy, deliverables and pricing.',
    report({ meta: [text('title', 'Campaign Name', { required: true }), text('author', 'Agency'), text('client', 'Client'), date()] }),
    { tags: ['marketing', 'proposal', 'agency', 'campaign'] }),
  T('social-media-calendar', 'Social Media Content Calendar', 'marketing', 'planner',
    'Plan social posts by date, platform and content type.',
    planner('Content Plan', [date('day', 'Date'), sel('platform', 'Platform', ['Instagram', 'Facebook', 'X/Twitter', 'LinkedIn', 'TikTok', 'YouTube']), text('content', 'Post / Content Idea', { span: 2 }), text('status', 'Status')]),
    { tags: ['social media', 'calendar', 'content', 'marketing'] }),
  T('campaign-brief', 'Campaign Brief', 'marketing', 'form',
    'Brief defining campaign goals, audience, message and budget.',
    form('main', 'Campaign', [
      text('title', 'Campaign Name', { required: true }), text('brand', 'Brand / Product'),
      date('start', 'Start Date'), date('end', 'End Date'), cur('budget', 'Budget'),
      long('objective', 'Objective', { span: 2 }), long('audience', 'Target Audience', { span: 2 }),
      long('message', 'Key Message', { span: 2 }), long('channels', 'Channels', { span: 2 }),
    ], ), { tags: ['campaign', 'brief', 'marketing', 'advertising'] }),
  T('press-release', 'Press Release', 'marketing', 'letter',
    'Standard press release format for announcing news.',
    letter({ subject: 'FOR IMMEDIATE RELEASE', greeting: '' }),
    { tags: ['press', 'release', 'pr', 'news', 'media'] }),
  T('newsletter', 'Newsletter', 'marketing', 'report',
    'Company newsletter layout with sections for updates and stories.',
    report({ meta: [text('title', 'Newsletter Title', { required: true }), text('issue', 'Issue No.'), date()] }),
    { tags: ['newsletter', 'email', 'marketing', 'updates'] }),
  T('feedback-form', 'Customer Feedback Form', 'marketing', 'form',
    'Collect customer feedback with ratings and comments.',
    [
      fields('main', 'Customer', [text('name', 'Name'), email(), date()]),
      group('items', 'Rate Your Experience', [text('area', 'Area', { span: 2 }), sel('rating', 'Rating', ['Excellent', 'Good', 'Average', 'Poor'])], { addLabel: 'Add area', min: 4 }),
      fields('extra', 'Comments', [long('comments', 'Additional Comments', { span: 2 })]),
    ], { tags: ['feedback', 'survey', 'customer', 'form'] }),

  // ============ PROJECT MANAGEMENT ============
  T('project-plan', 'Project Plan', 'project', 'report',
    'Full project plan: scope, milestones, resources and risks.',
    report({ meta: [text('title', 'Project Name', { required: true }), text('author', 'Project Manager'), date('start', 'Start'), date('end', 'End')] }),
    { tags: ['project', 'plan', 'management'] }),
  T('project-timeline', 'Project Timeline', 'project', 'planner',
    'Milestone timeline with phases, dates and owners.',
    planner('Milestones', [text('phase', 'Phase'), date('due', 'Due Date'), text('task', 'Deliverable', { span: 2 }), text('owner', 'Owner')]),
    { tags: ['timeline', 'milestones', 'project', 'gantt'] }),
  T('project-brief', 'Project Brief', 'project', 'form',
    'One-page brief: objectives, scope, deliverables and stakeholders.',
    form('main', 'Project', [
      text('title', 'Project Name', { required: true }), text('manager', 'Project Manager'),
      date('start', 'Start Date'), date('end', 'End Date'), cur('budget', 'Budget'),
      long('objective', 'Objective', { span: 2 }), long('scope', 'Scope', { span: 2 }),
      long('deliverables', 'Deliverables', { span: 2 }), long('stakeholders', 'Stakeholders', { span: 2 }),
    ], ), { tags: ['project', 'brief', 'scope'] }),
  T('task-list', 'Task List', 'project', 'checklist',
    'Project task list with owners and status notes.',
    checklist('Tasks'), { tags: ['tasks', 'todo', 'project', 'checklist'] }),
  T('project-checklist', 'Project Checklist', 'project', 'checklist',
    'End-to-end project checklist from kickoff to closure.',
    checklist('Checklist Items'), { tags: ['project', 'checklist', 'quality'] }),
  T('risk-register', 'Risk Register', 'project', 'table',
    'Log project risks with likelihood, impact and mitigation.',
    table('Risks', [text('risk', 'Risk', { span: 2 }), sel('level', 'Likelihood', ['Low', 'Medium', 'High']), sel('impact', 'Impact', ['Low', 'Medium', 'High']), text('mitigation', 'Mitigation')]),
    { tags: ['risk', 'register', 'project', 'management'] }),
  T('issue-tracker', 'Issue Tracker', 'project', 'table',
    'Track project issues with priority, owner and status.',
    table('Issues', [date('day', 'Date'), text('issue', 'Issue', { span: 2 }), sel('priority', 'Priority', ['High', 'Medium', 'Low']), text('owner', 'Owner'), text('status', 'Status')]),
    { tags: ['issues', 'tracker', 'bugs', 'project'] }),
  T('status-report', 'Project Status Report', 'project', 'report',
    'Weekly status report: progress, blockers, next steps.',
    report({ meta: [text('title', 'Project Name', { required: true }), text('author', 'Reporter'), text('period', 'Reporting Period'), date()] }),
    { tags: ['status', 'report', 'project', 'weekly'] }),
];
