// Template definitions: Finance, Education, Personal
const B = require('./seed_fields');
const { sender, party, fields, group, signBlock, docMeta, letter, form, cv, report, planner, table, checklist } = B;
const { text, long, num, cur, date, email, phone, sel, img, check, addr } = B;

const T = (slug, name, cat, doc, desc, sections, opts = {}) =>
  ({ slug, name, category: cat, docType: doc, description: desc, sections, tags: opts.tags || [], featured: !!opts.featured, disclaimer: opts.disclaimer });

module.exports = [

  // ============ FINANCE ============
  T('budget-planner', 'Budget Planner', 'finance', 'table',
    'Plan income and expenses by category with a running total.',
    table('Budget Items', [text('cat', 'Category'), text('desc', 'Description'), cur('income', 'Planned'), cur('spent', 'Actual')]),
    { tags: ['budget', 'planner', 'money', 'finance'], featured: true }),
  T('monthly-budget', 'Monthly Budget Sheet', 'finance', 'table',
    'Track monthly income, expenses and savings in one sheet.',
    table('Monthly Budget', [text('cat', 'Category'), cur('planned', 'Planned'), cur('actual', 'Actual'), text('note', 'Notes')]),
    { tags: ['budget', 'monthly', 'expenses', 'finance'] }),
  T('expense-tracker', 'Expense Tracker', 'finance', 'table',
    'Log daily expenses by date, category and amount.',
    table('Expenses', [date('day', 'Date'), text('cat', 'Category'), text('desc', 'Description'), cur('amount', 'Amount')]),
    { tags: ['expense', 'tracker', 'spending', 'finance'], featured: true }),
  T('income-tracker', 'Income Tracker', 'finance', 'table',
    'Record income sources and amounts over time.',
    table('Income', [date('day', 'Date'), text('source', 'Source'), cur('amount', 'Amount'), text('note', 'Notes')]),
    { tags: ['income', 'tracker', 'earnings', 'finance'] }),
  T('expense-claim', 'Expense Claim Form', 'finance', 'form',
    'Employee expense claim with itemized costs and approval.',
    [
      fields('main', 'Claimant', [text('name', 'Employee Name', { required: true }), text('dept', 'Department'), date(), text('purpose', 'Purpose / Trip')]),
      group('items', 'Expenses', [date('day', 'Date'), text('desc', 'Description', { span: 2 }), text('cat', 'Category'), cur('price', 'Amount')], { addLabel: 'Add expense', min: 3 }),
      signBlock(['Employee', 'Manager Approval']),
    ], { tags: ['expense', 'claim', 'reimbursement', 'finance'] }),
  T('reimbursement-form', 'Reimbursement Form', 'finance', 'form',
    'Request reimbursement for out-of-pocket expenses.',
    [
      fields('main', 'Requester', [text('name', 'Name', { required: true }), text('dept', 'Department'), date(), text('bank', 'Bank / IBAN')]),
      group('items', 'Items', [text('desc', 'Description', { span: 2 }), cur('price', 'Amount')], { addLabel: 'Add item', min: 2 }),
      signBlock(['Requester', 'Approver']),
    ], { tags: ['reimbursement', 'expense', 'finance', 'form'] }),
  T('financial-report', 'Financial Report', 'finance', 'report',
    'Periodic financial report: summary, income, expenses, notes.',
    report({ meta: [text('title', 'Report Title', { required: true }), text('author', 'Prepared By'), text('period', 'Period'), date()] }),
    { tags: ['financial', 'report', 'finance', 'statement'] }),
  T('payment-request', 'Payment Request Form', 'finance', 'form',
    'Internal form to request a payment to a vendor or person.',
    form('main', 'Payment Request', [
      text('payee', 'Payee Name', { required: true }), text('dept', 'Department'),
      cur('amount', 'Amount'), date('needed', 'Date Needed'),
      sel('method', 'Payment Method', ['Bank Transfer', 'Cheque', 'Cash', 'Card']),
      text('ref', 'Invoice / Reference'),
      long('reason', 'Reason for Payment', { span: 2 }),
    ]), { tags: ['payment', 'request', 'finance', 'approval'] }),

  // ============ EDUCATION ============
  T('student-resume', 'Student Resume', 'education', 'cv',
    'Resume for students: education first, projects, skills, activities.',
    cv(), { tags: ['resume', 'cv', 'student', 'internship'] }),
  T('scholarship-application', 'Scholarship Application', 'education', 'form',
    'Application form for scholarships with academic and financial info.',
    form('main', 'Applicant Information', [
      text('name', 'Full Name', { required: true }), date('dob', 'Date of Birth'),
      email(), phone(), addr(),
      text('school', 'Current School / University'), text('gpa', 'GPA / Grade'),
      text('program', 'Program Applied For'),
      long('statement', 'Personal Statement', { span: 2 }),
      long('need', 'Financial Need / Circumstances', { span: 2 }),
    ]), { tags: ['scholarship', 'application', 'student', 'education'] }),
  T('study-planner', 'Study Planner', 'education', 'planner',
    'Weekly study schedule with subjects, times and goals.',
    planner('Study Sessions', [text('day', 'Day'), text('time', 'Time'), text('subject', 'Subject'), text('goal', 'Goal')]),
    { tags: ['study', 'planner', 'schedule', 'student'] }),
  T('assignment-cover', 'Assignment Cover Page', 'education', 'form',
    'Cover page for assignments with course and submission details.',
    [
      fields('main', 'Assignment Details', [
        text('title', 'Assignment Title', { required: true }), text('course', 'Course / Code'),
        text('instructor', 'Instructor'), text('name', 'Student Name'),
        text('studentid', 'Student ID'), date('due', 'Submission Date'),
      ]),
    ], { tags: ['assignment', 'cover', 'school', 'university'] }),
  T('research-proposal', 'Research Proposal', 'education', 'report',
    'Academic research proposal: title, background, methods, timeline.',
    report({ meta: [text('title', 'Research Title', { required: true }), text('author', 'Researcher'), text('dept', 'Department'), date()] }),
    { tags: ['research', 'proposal', 'academic', 'thesis'] }),
  T('class-schedule', 'Class Schedule', 'education', 'planner',
    'Weekly class timetable with periods and rooms.',
    planner('Classes', [text('day', 'Day'), text('time', 'Time'), text('subject', 'Subject'), text('room', 'Room')]),
    { tags: ['schedule', 'class', 'timetable', 'school'] }),
  T('lesson-plan', 'Lesson Plan', 'education', 'form',
    'Teacher lesson plan: objectives, activities, assessment.',
    [
      fields('main', 'Lesson', [text('title', 'Lesson Title', { required: true }), text('subject', 'Subject'), text('grade', 'Grade Level'), date(), text('duration', 'Duration')]),
      fields('plan', 'Plan', [long('objectives', 'Learning Objectives', { span: 2 }), long('materials', 'Materials Needed', { span: 2 }), long('activities', 'Activities / Procedure', { span: 2 }), long('assessment', 'Assessment', { span: 2 }), long('homework', 'Homework', { span: 2 })]),
    ], { tags: ['lesson', 'plan', 'teacher', 'education'] }),
  T('student-information', 'Student Information Form', 'education', 'form',
    'Enrollment form collecting student and guardian details.',
    form('main', 'Student Information', [
      text('name', 'Student Name', { required: true }), date('dob', 'Date of Birth'),
      text('grade', 'Grade / Class'), addr(),
      text('guardian', 'Parent / Guardian'), phone('gphone', 'Guardian Phone'),
      long('medical', 'Medical Notes / Allergies', { span: 2 }),
      long('emergency', 'Emergency Contact', { span: 2 }),
    ]), { tags: ['student', 'information', 'enrollment', 'school'] }),
  T('school-permission-letter', 'School Permission Letter', 'education', 'letter',
    'Parent permission letter for trips, activities or absences.',
    letter({ subject: 'Permission for [Activity]', greeting: 'Dear [Teacher/Principal],' }),
    { tags: ['permission', 'school', 'letter', 'parent'] }),

  // ============ PERSONAL ============
  T('personal-budget', 'Personal Budget', 'personal', 'table',
    'Simple personal budget for tracking income and expenses.',
    table('Budget', [text('cat', 'Category'), cur('planned', 'Planned'), cur('actual', 'Actual'), text('note', 'Notes')]),
    { tags: ['budget', 'personal', 'money', 'savings'] }),
  T('daily-planner', 'Daily Planner', 'personal', 'planner',
    'Hour-by-hour daily planner with tasks and notes.',
    planner('Schedule', [text('time', 'Time'), text('task', 'Task', { span: 2 }), check('done', 'Done')]),
    { tags: ['planner', 'daily', 'schedule', 'productivity'], featured: true }),
  T('weekly-planner', 'Weekly Planner', 'personal', 'planner',
    'Plan your week day by day with priorities and notes.',
    planner('Week', [text('day', 'Day'), text('task', 'Tasks / Priorities', { span: 2 }), text('note', 'Notes')], ),
    { tags: ['planner', 'weekly', 'schedule', 'productivity'] }),
  T('to-do-list', 'To-Do List', 'personal', 'checklist',
    'Simple printable to-do list with checkboxes.',
    checklist('Tasks'), { tags: ['todo', 'tasks', 'checklist', 'productivity'] }),
  T('shopping-list', 'Shopping List', 'personal', 'checklist',
    'Grocery and shopping list organized with notes.',
    checklist('Shopping Items'), { tags: ['shopping', 'grocery', 'list'] }),
  T('meal-planner', 'Meal Planner', 'personal', 'planner',
    'Weekly meal planner with breakfast, lunch and dinner slots.',
    planner('Meals', [text('day', 'Day'), text('breakfast', 'Breakfast'), text('lunch', 'Lunch'), text('dinner', 'Dinner')]),
    { tags: ['meal', 'planner', 'food', 'weekly'] }),
  T('travel-planner', 'Travel Planner', 'personal', 'planner',
    'Trip planner with dates, destinations, bookings and activities.',
    planner('Itinerary', [date('day', 'Date'), text('place', 'Place'), text('activity', 'Activity / Booking'), text('note', 'Notes')]),
    { tags: ['travel', 'planner', 'trip', 'itinerary'] }),
  T('emergency-contact', 'Emergency Contact Form', 'personal', 'form',
    'Keep emergency contacts, doctors and key info in one sheet.',
    form('main', 'Emergency Information', [
      text('name', 'Your Name', { required: true }), phone(), addr(),
      long('contacts', 'Emergency Contacts (name, relation, phone)', { span: 2 }),
      text('doctor', 'Family Doctor'), text('insurance', 'Insurance / Policy No.'),
      long('medical', 'Medical Conditions / Allergies', { span: 2 }),
    ], ), { tags: ['emergency', 'contact', 'safety', 'family'] }),
  T('authorization-letter', 'Authorization Letter', 'personal', 'letter',
    'Letter authorizing someone to act on your behalf.',
    letter({ subject: 'Letter of Authorization', greeting: 'To Whom It May Concern,' }),
    { tags: ['authorization', 'letter', 'permission'] }),
  T('complaint-letter', 'Complaint Letter', 'personal', 'letter',
    'Formal complaint letter to a company or organization.',
    letter({ subject: 'Formal Complaint' }),
    { tags: ['complaint', 'letter', 'formal'] }),
];
