// Template definitions: Sales & Invoicing, Freelancers, HR
const B = require('./seed_fields');
const { sender, party, fields, group, signBlock, docMeta, letter, form, report, planner, table, moneyDoc, notesTerms, moneyItems, agreement } = B;
const { text, long, num, cur, date, email, phone, sel, img, check, addr } = B;

const T = (slug, name, cat, doc, desc, sections, opts = {}) =>
  ({ slug, name, category: cat, docType: doc, description: desc, sections, tags: opts.tags || [], featured: !!opts.featured, disclaimer: opts.disclaimer });

module.exports = [

  // ============ SALES & INVOICING ============
  T('professional-invoice', 'Professional Invoice', 'sales-invoicing', 'invoice',
    'Clean professional invoice with itemized billing, tax and totals.',
    moneyDoc({ meta: [text('no', 'Invoice No.', { required: true }), date('date', 'Invoice Date'), date('due', 'Due Date')] }),
    { tags: ['invoice', 'billing', 'payment', 'sales'], featured: true }),
  T('tax-invoice', 'Tax Invoice', 'sales-invoicing', 'invoice',
    'Invoice with tax breakdown per line item and tax registration field.',
    moneyDoc({ meta: [text('no', 'Invoice No.', { required: true }), date(), text('taxid', 'Tax / VAT ID'), date('due', 'Due Date')] }),
    { tags: ['invoice', 'tax', 'vat', 'billing'] }),
  T('service-invoice', 'Service Invoice', 'sales-invoicing', 'invoice',
    'Invoice for services rendered with hourly or fixed-rate lines.',
    moneyDoc({ meta: [text('no', 'Invoice No.', { required: true }), date(), date('due', 'Due Date'), text('po', 'PO Reference')] }),
    { tags: ['invoice', 'service', 'billing'] }),
  T('proforma-invoice', 'Proforma Invoice', 'sales-invoicing', 'invoice',
    'Preliminary invoice sent before goods or services are delivered.',
    moneyDoc({ meta: [text('no', 'Proforma No.'), date(), date('valid', 'Valid Until')] }),
    { tags: ['invoice', 'proforma', 'export', 'quote'] }),
  T('commercial-invoice', 'Commercial Invoice', 'sales-invoicing', 'invoice',
    'Commercial invoice for international shipments and customs.',
    moneyDoc({ meta: [text('no', 'Invoice No.'), date(), text('country', 'Country of Origin'), text('incoterm', 'Incoterms')] }),
    { tags: ['invoice', 'commercial', 'export', 'customs'] }),
  T('business-quotation', 'Business Quotation', 'sales-invoicing', 'invoice',
    'Formal price quotation with items, terms and validity period.',
    moneyDoc({ client: 'Customer', meta: [text('no', 'Quote No.'), date(), date('valid', 'Valid Until')] }),
    { tags: ['quotation', 'quote', 'price', 'sales'], featured: true }),
  T('price-quote', 'Price Quote', 'sales-invoicing', 'invoice',
    'Quick price quote for products or services.',
    moneyDoc({ client: 'Customer', meta: [text('no', 'Quote No.'), date()] }),
    { tags: ['quote', 'price', 'estimate'] }),
  T('sales-order', 'Sales Order', 'sales-invoicing', 'invoice',
    'Sales order confirmation listing items, quantities and delivery.',
    moneyDoc({ client: 'Customer', meta: [text('no', 'Order No.'), date(), date('ship', 'Ship Date')] }),
    { tags: ['order', 'sales', 'confirmation'] }),
  T('purchase-order', 'Purchase Order', 'sales-invoicing', 'invoice',
    'Purchase order sent to a supplier listing items and terms.',
    moneyDoc({ company: 'Buyer', client: 'Supplier', meta: [text('no', 'PO No.', { required: true }), date(), date('deliver', 'Required By')] }),
    { tags: ['purchase', 'order', 'po', 'supplier'], featured: true }),
  T('payment-receipt', 'Payment Receipt', 'sales-invoicing', 'receipt',
    'Acknowledgement of payment received with method and reference.',
    B.receiptDoc(), { tags: ['receipt', 'payment', 'acknowledgement'] }),
  T('delivery-note', 'Delivery Note', 'sales-invoicing', 'invoice',
    'Delivery note listing shipped items and quantities for sign-off.',
    moneyDoc({ client: 'Deliver To', meta: [text('no', 'Delivery Note No.'), date(), text('order', 'Order Ref')] }),
    { tags: ['delivery', 'note', 'shipping', 'goods'] }),
  T('credit-note', 'Credit Note', 'sales-invoicing', 'invoice',
    'Credit note issued for returns, refunds or overpayments.',
    moneyDoc({ meta: [text('no', 'Credit Note No.'), date(), text('inv', 'Original Invoice No.')] }),
    { tags: ['credit', 'note', 'refund', 'return'] }),

  // ============ FREELANCERS & AGENCIES ============
  T('freelance-proposal', 'Freelance Proposal', 'freelance', 'report',
    'Win client work with a proposal covering scope, timeline and pricing.',
    report({ meta: [text('title', 'Project Title', { required: true }), text('author', 'Freelancer'), text('client', 'Client'), date()] }),
    { tags: ['freelance', 'proposal', 'client', 'project'] }),
  T('freelance-contract', 'Freelance Contract', 'freelance', 'agreement',
    'Contract between freelancer and client covering deliverables and payment.',
    agreement({ a: 'Freelancer', b: 'Client' }),
    { tags: ['freelance', 'contract', 'agreement'], disclaimer: true }),
  T('client-brief', 'Client Brief', 'freelance', 'form',
    'Intake form capturing a client\u2019s goals, audience and requirements.',
    [
      fields('main', 'Client Information', [text('name', 'Client Name', { required: true }), text('company', 'Company'), email(), phone(), text('website', 'Website')]),
      fields('project', 'Project Brief', [text('title', 'Project Name'), text('budget', 'Budget Range'), date('deadline', 'Deadline'), long('goals', 'Project Goals', { span: 2 }), long('audience', 'Target Audience', { span: 2 }), long('requirements', 'Requirements & Deliverables', { span: 2 })]),
    ], { tags: ['client', 'brief', 'intake', 'onboarding'] }),
  T('client-onboarding', 'Client Onboarding Form', 'freelance', 'form',
    'Onboarding checklist and info form for new clients.',
    [
      fields('main', 'Client Details', [text('name', 'Client Name', { required: true }), text('company', 'Company'), email(), phone(), text('billing', 'Billing Contact')]),
      fields('access', 'Access & Assets', [long('access', 'Accounts / Access Provided', { span: 2 }), long('assets', 'Brand Assets Received', { span: 2 })]),
      fields('prefs', 'Preferences', [text('comms', 'Preferred Communication'), text('updates', 'Update Frequency'), long('notes', 'Notes', { span: 2 })]),
    ], { tags: ['onboarding', 'client', 'form'] }),
  T('statement-of-work', 'Statement of Work (SOW)', 'freelance', 'report',
    'Detailed SOW: scope, deliverables, milestones, acceptance criteria.',
    report({ meta: [text('title', 'Project Name', { required: true }), text('author', 'Contractor'), text('client', 'Client'), date(), cur('amount', 'Total Fee')] }),
    { tags: ['sow', 'scope', 'work', 'contract'] }),
  T('project-estimate', 'Project Estimate', 'freelance', 'invoice',
    'Itemized estimate of project costs for client approval.',
    moneyDoc({ client: 'Client', meta: [text('no', 'Estimate No.'), date(), date('valid', 'Valid Until')] }),
    { tags: ['estimate', 'quote', 'project', 'cost'] }),
  T('payment-reminder', 'Payment Reminder Letter', 'freelance', 'letter',
    'Polite reminder letter for an outstanding invoice.',
    letter({ subject: 'Payment Reminder — Invoice [No.]' }),
    { tags: ['payment', 'reminder', 'invoice', 'overdue'] }),

  // ============ HR & EMPLOYEES ============
  T('employee-application', 'Employee Application Form', 'hr', 'form',
    'HR application form for collecting candidate and employment details.',
    form('main', 'Employee Information', [
      text('name', 'Full Name', { required: true }), date('dob', 'Date of Birth'),
      email(), phone(), addr(),
      text('position', 'Position'), text('dept', 'Department'), date('start', 'Start Date'),
      sel('type', 'Employment Type', ['Full-time', 'Part-time', 'Contract']),
      long('emergency', 'Emergency Contact (name & phone)', { span: 2 }),
    ]), { tags: ['employee', 'application', 'hr', 'form'] }),
  T('employee-information', 'Employee Information Form', 'hr', 'form',
    'Personal and payroll information form for new employees.',
    form('main', 'Employee Details', [
      text('name', 'Full Name', { required: true }), text('empid', 'Employee ID'),
      email(), phone(), addr(),
      date('dob', 'Date of Birth'), text('bank', 'Bank / IBAN'),
      long('emergency', 'Emergency Contact', { span: 2 }),
    ]), { tags: ['employee', 'information', 'hr', 'onboarding'] }),
  T('offer-letter', 'Offer Letter', 'hr', 'letter',
    'Employment offer letter stating role, compensation and start date.',
    [
      sender('Company Details'),
      fields('doc', 'Offer Details', [date(), text('position', 'Position', { required: true }), cur('salary', 'Salary'), date('start', 'Start Date')]),
      party('recipient', 'Candidate'),
      fields('body', 'Message', [text('greeting', 'Salutation', { default: 'Dear [Candidate Name],' }), long('body', 'Letter body', { span: 2 }), text('closing', 'Closing', { default: 'Sincerely,' }), text('signName', 'Authorized signatory')]),
    ], { tags: ['offer', 'letter', 'employment', 'hr'] }),
  T('employment-contract', 'Employment Contract', 'hr', 'agreement',
    'Contract of employment covering role, pay, hours and termination.',
    agreement({ a: 'Employer', b: 'Employee' }),
    { tags: ['employment', 'contract', 'hr'], disclaimer: true }),
  T('experience-letter', 'Experience Letter', 'hr', 'letter',
    'Letter certifying an employee\u2019s role and duration of service.',
    letter({ subject: 'Experience Certificate', greeting: 'To Whom It May Concern,' }),
    { tags: ['experience', 'certificate', 'employment', 'hr'] }),
  T('salary-certificate', 'Salary Certificate', 'hr', 'letter',
    'Certificate confirming an employee\u2019s salary for banks and embassies.',
    letter({ subject: 'Salary Certificate', greeting: 'To Whom It May Concern,' }),
    { tags: ['salary', 'certificate', 'hr', 'income'] }),
  T('warning-letter', 'Employee Warning Letter', 'hr', 'letter',
    'Formal written warning documenting a conduct or performance issue.',
    letter({ subject: 'Written Warning' }),
    { tags: ['warning', 'discipline', 'hr', 'letter'] }),
  T('leave-application', 'Leave Application', 'hr', 'form',
    'Employee leave request form with dates, type and reason.',
    form('main', 'Leave Request', [
      text('name', 'Employee Name', { required: true }), text('empid', 'Employee ID'),
      sel('type', 'Leave Type', ['Annual', 'Sick', 'Casual', 'Maternity/Paternity', 'Unpaid', 'Other']),
      date('from', 'From Date'), date('to', 'To Date'),
      num('days', 'Total Days'), text('manager', 'Manager'),
      long('reason', 'Reason', { span: 2 }),
    ]), { tags: ['leave', 'vacation', 'request', 'hr'] }),
  T('termination-letter', 'Termination Letter', 'hr', 'letter',
    'Letter formally ending an employment relationship.',
    letter({ subject: 'Termination of Employment' }),
    { tags: ['termination', 'dismissal', 'hr', 'letter'] }),
  T('performance-review', 'Performance Review Form', 'hr', 'form',
    'Annual review form with ratings, achievements and goals.',
    [
      fields('main', 'Employee', [text('name', 'Employee Name', { required: true }), text('dept', 'Department'), text('reviewer', 'Reviewer'), date('date', 'Review Date')]),
      group('items', 'Review Areas', [text('area', 'Area / Competency', { span: 2 }), sel('rating', 'Rating', ['Excellent', 'Good', 'Satisfactory', 'Needs Improvement']), text('comment', 'Comment')], { addLabel: 'Add area', min: 4 }),
      fields('extra', 'Summary', [long('achievements', 'Key Achievements', { span: 2 }), long('goals', 'Goals for Next Period', { span: 2 })]),
      signBlock(['Employee', 'Reviewer']),
    ], { tags: ['performance', 'review', 'appraisal', 'hr'] }),
  T('attendance-sheet', 'Attendance Sheet', 'hr', 'table',
    'Daily attendance register with name, in/out times and signature.',
    table('Attendance', [text('name', 'Employee Name'), text('in', 'Time In'), text('out', 'Time Out'), text('sign', 'Signature')]),
    { tags: ['attendance', 'register', 'hr', 'timesheet'] }),
  T('timesheet', 'Employee Timesheet', 'hr', 'table',
    'Weekly timesheet recording hours worked per day.',
    table('Time Entries', [date('day', 'Date'), text('task', 'Task / Project'), num('hours', 'Hours'), text('note', 'Notes')]),
    { tags: ['timesheet', 'hours', 'hr', 'work log'] }),
];
