// Template definitions: Career & Jobs + Business
const B = require('./seed_fields');
const { sender, party, fields, group, signBlock, docMeta, letter, form, cv, report, planner, table, moneyDoc, notesTerms, moneyItems } = B;
const { text, long, num, cur, date, email, phone, sel, img, check, addr } = B;

const T = (slug, name, cat, doc, desc, sections, opts = {}) =>
  ({ slug, name, category: cat, docType: doc, description: desc, sections, tags: opts.tags || [], featured: !!opts.featured, disclaimer: opts.disclaimer });

module.exports = [

  // ============ CAREER & JOBS ============
  T('modern-resume', 'Modern Resume', 'career', 'cv',
    'A clean modern resume layout with sections for summary, experience, education and skills.',
    cv(), { tags: ['resume', 'cv', 'job', 'career'], featured: true }),
  T('professional-resume', 'Professional Resume', 'career', 'cv',
    'Classic professional resume for corporate and senior roles.',
    cv(), { tags: ['resume', 'cv', 'job', 'professional'] }),
  T('ats-resume', 'ATS Resume', 'career', 'cv',
    'Simple single-column resume optimised for applicant tracking systems.',
    cv(), { tags: ['resume', 'cv', 'ats', 'job'] }),
  T('cover-letter', 'Cover Letter', 'career', 'letter',
    'Professional cover letter to accompany a job application.',
    letter({ subject: 'Application for [Position]', greeting: 'Dear Hiring Manager,' }),
    { tags: ['cover letter', 'job', 'application'], featured: true }),
  T('job-application', 'Job Application Form', 'career', 'form',
    'Standard employment application form collecting candidate details.',
    form('main', 'Applicant Information', [
      text('name', 'Full Name', { required: true }), text('position', 'Position Applied For'),
      email(), phone(), addr(),
      date('available', 'Available Start Date'),
      sel('type', 'Employment Type', ['Full-time', 'Part-time', 'Contract', 'Internship']),
      long('experience', 'Relevant Experience', { span: 2 }),
      long('reason', 'Why should we hire you?', { span: 2 }),
      check('consent', 'I confirm the information provided is accurate'),
    ]), { tags: ['job', 'application', 'employment', 'form'] }),
  T('reference-sheet', 'Professional Reference Sheet', 'career', 'table',
    'A tidy sheet listing professional references for job applications.',
    table('References', [text('name', 'Name'), text('company', 'Company'), text('title', 'Title'), phone(), email()]),
    { tags: ['references', 'job', 'resume'] }),
  T('resignation-letter', 'Resignation Letter', 'career', 'letter',
    'Formal resignation letter with notice period and handover note.',
    letter({ subject: 'Resignation Notice', greeting: 'Dear [Manager Name],' }),
    { tags: ['resignation', 'quit', 'notice', 'letter'] }),
  T('job-offer-letter', 'Job Offer Letter', 'career', 'letter',
    'Formal offer of employment including position, salary and start date.',
    [
      sender('Company Details'),
      fields('doc', 'Offer Details', [date(), text('position', 'Position', { required: true }), cur('salary', 'Salary'), date('start', 'Start Date'), sel('type', 'Employment Type', ['Full-time', 'Part-time', 'Contract'])]),
      party('recipient', 'Candidate'),
      fields('body', 'Message', [text('greeting', 'Salutation', { default: 'Dear [Candidate Name],' }), long('body', 'Letter body', { span: 2 }), text('closing', 'Closing', { default: 'Sincerely,' }), text('signName', 'Authorized signatory')]),
    ], { tags: ['offer', 'job', 'employment', 'letter'] }),
  T('employment-verification-letter', 'Employment Verification Letter', 'career', 'letter',
    'Letter confirming an employee\u2019s role, tenure and salary for third parties.',
    letter({ subject: 'Employment Verification', greeting: 'To Whom It May Concern,' }),
    { tags: ['verification', 'employment', 'hr', 'letter'] }),
  T('recommendation-letter', 'Recommendation Letter', 'career', 'letter',
    'Letter recommending a candidate for a job, scholarship or program.',
    letter({ subject: 'Letter of Recommendation', greeting: 'Dear Sir/Madam,' }),
    { tags: ['recommendation', 'reference', 'letter', 'job'] }),
  T('thank-you-letter', 'Interview Thank You Letter', 'career', 'letter',
    'Polite follow-up letter thanking an interviewer after a job interview.',
    letter({ subject: 'Thank You — [Position] Interview', greeting: 'Dear [Interviewer Name],' }),
    { tags: ['thank you', 'interview', 'follow up', 'letter'] }),
  T('salary-increment-letter', 'Salary Increment Letter', 'career', 'letter',
    'Formal letter notifying an employee of a salary increase.',
    letter({ subject: 'Salary Increment Notification' }),
    { tags: ['salary', 'increment', 'raise', 'letter'] }),

  // ============ BUSINESS ============
  T('business-proposal', 'Business Proposal', 'business', 'report',
    'A structured proposal to pitch products, services or a partnership.',
    report({ meta: [text('title', 'Proposal Title', { required: true }), text('author', 'Prepared By'), text('client', 'Prepared For'), date()] }),
    { tags: ['proposal', 'business', 'pitch'], featured: true }),
  T('business-plan', 'Business Plan', 'business', 'report',
    'Full business plan outline: summary, market, strategy, operations, finances.',
    report({ meta: [text('title', 'Business Name', { required: true }), text('author', 'Prepared By'), date()] }),
    { tags: ['business plan', 'strategy', 'startup'] }),
  T('company-profile', 'Company Profile', 'business', 'report',
    'Professional company profile: overview, services, milestones, contacts.',
    report({ meta: [text('title', 'Company Name', { required: true }), text('author', 'Prepared By'), date()] }),
    { tags: ['company', 'profile', 'overview'] }),
  T('project-proposal', 'Project Proposal', 'business', 'report',
    'Proposal defining project scope, deliverables, timeline and budget.',
    report({ meta: [text('title', 'Project Name', { required: true }), text('author', 'Prepared By'), text('client', 'Client'), date()] }),
    { tags: ['project', 'proposal', 'scope'] }),
  T('partnership-proposal', 'Partnership Proposal', 'business', 'report',
    'Proposal outlining a business partnership opportunity and terms.',
    report(), { tags: ['partnership', 'proposal', 'business'] }),
  T('business-letter', 'Formal Business Letter', 'business', 'letter',
    'Standard formal business letter with letterhead layout.',
    letter(), { tags: ['business', 'letter', 'formal', 'correspondence'] }),
  T('business-memo', 'Business Memo', 'business', 'letter',
    'Internal memo template for company announcements and updates.',
    letter({ subject: 'MEMO', greeting: 'To All Staff,' }),
    { tags: ['memo', 'internal', 'business'] }),
  T('meeting-agenda', 'Meeting Agenda', 'business', 'planner',
    'Timed meeting agenda with topics, owners and notes.',
    planner('Agenda Items', [text('time', 'Time'), text('topic', 'Topic', { span: 2 }), text('owner', 'Owner')]),
    { tags: ['meeting', 'agenda', 'schedule'] }),
  T('meeting-minutes', 'Meeting Minutes', 'business', 'form',
    'Record of attendees, discussions, decisions and action items.',
    [
      fields('main', 'Meeting Information', [text('title', 'Meeting Title', { required: true }), date(), text('time', 'Time'), text('location', 'Location'), long('attendees', 'Attendees', { span: 2 }), long('absent', 'Absent', { span: 2 })]),
      group('items', 'Discussion & Action Items', [text('topic', 'Topic / Decision', { span: 2 }), text('owner', 'Owner'), text('due', 'Due Date')], { addLabel: 'Add item', min: 4 }),
      fields('extra', 'Notes', [long('notes', 'Additional Notes', { span: 2 })]),
      signBlock(['Prepared By']),
    ], { tags: ['meeting', 'minutes', 'notes', 'record'] }),
  T('business-agreement', 'Business Agreement', 'business', 'agreement',
    'General agreement between two businesses covering scope and terms.',
    B.agreement({ a: 'Company A', b: 'Company B' }),
    { tags: ['agreement', 'contract', 'business'], disclaimer: true }),
  T('terms-conditions', 'Terms & Conditions', 'business', 'agreement',
    'Website or service terms & conditions skeleton.',
    B.agreement({ a: 'Service Provider', b: 'User / Customer', details: [date('date', 'Effective Date'), text('ref', 'Version')] }),
    { tags: ['terms', 'conditions', 'policy', 'website'], disclaimer: true }),
  T('sop', 'Standard Operating Procedure (SOP)', 'business', 'report',
    'Step-by-step SOP document: purpose, scope, procedure, responsibilities.',
    report({ meta: [text('title', 'Procedure Title', { required: true }), text('dept', 'Department'), text('version', 'Version'), date('date', 'Effective Date')] }),
    { tags: ['sop', 'procedure', 'process', 'operations'] }),
];
